config/routes.rb
Valueneeds::Application.routes.draw do

  resources :bottom_banners

  resources :password_resets

  resources :recipes do
    get :recipes_description, :on => :collection
  end

  resources :galleries do
  get :create_gallery, :on => :collection
  end
  resources :wish_lists

  resources :wallet_entries do
    get :my_wallet, :on => :collection
    get :show_wallet, :on => :collection
  end

  resources :notify_me_requests

  resources :delivery_slot_names do
    get :slots_for_mobile, :on => :collection
  end

  resources :pincodes do
    get :users_index, :on => :collection
  end

  resources :system_settings

  resources :product_attributes

  resources :attribute_items

  resources :attributes

  resources :scroll_texts

  resources :specialities

  get "static/contact_us"
  get "static/about_us"
  get "static/faq"
  get "static/privacy_policy"
  get "static/terms_and_conditions"
  get "static/delivery_information"
  get "static/refund_and_return_policy"
  get "static/follow_us"
  get "static/site_map"
  get "static/where_we_deliver"
  get "static/general_information"
  get "static/need_assistance"
  get "static/customer_service"
  get "static/getting_started"
  get "static/vn_offers"
  get "static/coupon_and_vouchers"
  get "static/news_and_events"
  get "static/winners"
  get "static/dataFrom"
  get "static/ccavRequestHandler"
  post "static/payment_response_handler"
  resources :slide_images

  resources :user_sessions

  resources :promo_groups

  resources :product_price_ranges do
    get :load_product_price_range_ids, :on => :collection
    get :get_product_price_range, :on => :collection
  end

  resources :promos do
    get :load_all_promo_ids, :on => :collection
    get :get_promos_by_group, :on => :collection
    get :promo_offers, :on => :collection
    get :promo_complete_details, :on => :collection
    get :get_promo_offer_details, :on => :collection
  end

  resources :delivery_slots do
  get :create_delivery_slots, :on => :collection
  end

  resources :feedbacks

  resources :address_details do
    get :check_out, :on => :collection
    post :create_order_with_previous_address, :on => :collection
    get :get_address_details, :on => :collection
    get :get_delivery_slots, :on => :collection
    get :pay_with_wallet, :on => :collection
    get :confirm_with_wallet, :on => :collection
    post :create_order_with_new_address, :on => :collection
    get :create_order_from_payment_gateway, :on => :collection
  end

  resources :orders do
    get :get_previous_orders, :on => :collection
    get :repeat_order, :on => :collection
    get :invoice_status_details, :on => :collection
    get :order_tracking, :on => :collection
    get :status, :on => :collection
    get :payment_status, :on => :collection
    get :order_status_details, :on => :collection

  end

  resources :users do
    post :update_user_details, :on => :collection
  end

  resources :products do
    get :add_child_form, :on=> :collection
    post :update_category_child, :on => :collection
    get :remove_category, :on => :collection
    post :update_product_location_prices, :on => :collection
    get :add_product_location_price_form, :on => :collection
    get :remove_location_price, :on => :collection
    get :order_online, :on => :collection
    get :add_items_to_cart, :on => :collection
    get :remove_order_item, :on => :collection
    get :show_cart, :on => :collection
    get :login_screen, :on => :collection
    get :remove_order, :on => :collection
    get :update_location, :on => :collection
    get :empty_cart, :on => :collection
    get :get_products, :on => :collection
    get :get_products_by_ids, :on => :collection
    get :load_auto_complete_search_products, :on => :collection
    get :clear_auto_complete_text, :on => :collection
    get :get_main_filtered_products, :on => :collection
    get :show_search_products, :on => :collection
    get :product_details_tab, :on => :collection
    get :product_request, :on => :collection
    get :request_products, :on => :collection
    get :clean_orders, :on => :collection
    get :change_product_selection_quantity, :on => :collection
    get :change_product_tab_selection_quantity, :on => :collection
    get :edit_product, :on => :collection
    get :add_items_to_wish_list, :on => :collection
    get :show_wish_list_products, :on => :collection
    get :remove_wish_list_items, :on => :collection
    get :load_more, :on => :collection
  end

  resources :categories do
    get :get_child_categories, :on => :collection
    get :update_sequence_ids, :on => :collection
    get :change_category_sequence_order, :on => :collection
  end

  resources :locations

  resources :brands do
    get :get_brands_by_ids, :on => :collection
  end
  match 'promo-details/:title/:promo_id', :controller => 'promos', :action => 'promo_complete_details'
  match 'order-products', :controller => 'products', :action => 'order_online'
  match 'login', :controller => 'user_sessions', :action => 'new'
  match 'wallet', :controller => 'wallet_entries', :action => 'my_wallet'
  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'auth/:provider/callback', :to => 'user_sessions#log_in_with_others'
  match 'log_in_with_email', :to => 'user_sessions#log_in_with_email'
  match 'reset-password', :controller => 'password_resets', :action => 'new'

  match 'auth/failure', to: redirect('/')

   root :to => 'products#order_online'

end

app/models/promo_group.rb
class PromoGroup < ActiveRecord::Base
end

app/controllers/promo_groups_controller.rb
class PromoGroupsController < ApplicationController
  filter_resource_access
  # GET /promo_groups
  # GET /promo_groups.json
  def index
    @promo_groups = PromoGroup.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promo_groups }
    end
  end

  # GET /promo_groups/1
  # GET /promo_groups/1.json
  def show
    @promo_group = PromoGroup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promo_group }
    end
  end

  # GET /promo_groups/new
  # GET /promo_groups/new.json
  def new
    @promo_group = PromoGroup.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promo_group }
    end
  end

  # GET /promo_groups/1/edit
  def edit
    @promo_group = PromoGroup.find(params[:id])
  end

  # POST /promo_groups
  # POST /promo_groups.json
  def create
    @promo_group = PromoGroup.new
    update_group_category
    respond_to do |format|
      if @promo_group.save
        format.html { redirect_to @promo_group, notice: 'Promo group was successfully created.' }
        format.json { render json: @promo_group, status: :created, location: @promo_group }
      else
        format.html { render action: "new" }
        format.json { render json: @promo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promo_groups/1
  # PUT /promo_groups/1.json
  def update
    @promo_group = PromoGroup.find(params[:id])
    update_group_category
    respond_to do |format|
      if @promo_group.save
        format.html { redirect_to @promo_group, notice: 'Promo group was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @promo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promo_groups/1
  # DELETE /promo_groups/1.json
  def destroy
    @promo_group = PromoGroup.find(params[:id])
    @promo_group.destroy

    respond_to do |format|
      format.html { redirect_to promo_groups_url }
      format.json { head :ok }
    end
  end

  def update_group_category
    @promo_group.title = params[:promo_group][:title]
    @promo_group.description = params[:promo_group][:description]
    @promo_group.active = params[:promo_group][:active]
    uploaded_io = params[:promo_group][:image]
    if uploaded_io
      file_path_name = UUIDTools::UUID.random_create.to_s.delete '-'
      just_filename = File.basename(uploaded_io.original_filename)
      file_path_name += just_filename.sub(/[^\w\.\-]/, '_')
      File.open(Rails.root.join('public', 'product-group', file_path_name), 'w+b') do |file|
        file.write(uploaded_io.read)
      end
      puts "-----------------"
      puts file_path_name
      @promo_group.image = file_path_name
    end
  end
end

app/helpers/promo_groups_helper.rb
module PromoGroupsHelper
end

app/views/promo_groups/_form.html.erb
<%= form_for(@promo_group) do |f| %>
  <% if @promo_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo_group.errors.count, "error") %> prohibited this promo_group from being saved:</h2>

      <ul>
      <% @promo_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :size => "45x5" %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promo_groups/edit.html.erb
<h1>Editing promo_group</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo_group %> |
<%= link_to 'Back', promo_groups_path %>

app/views/promo_groups/index.html.erb
<h1>Listing Promo Groups</h1>

<table width="70%" border="1" cellspacing="5" cellpadding="5">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Image</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promo_groups.each do |promo_group| %>
  <tr>
    <td><%= promo_group.title %></td>
    <td><%= promo_group.description %></td>
    <td><%= promo_group.image %></td>
    <td><%= promo_group.active %></td>
    <td><%= link_to 'Show', promo_group %></td>
    <td><%= link_to 'Edit', edit_promo_group_path(promo_group) %></td>
    <td><%= link_to 'Destroy', promo_group, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promo group', new_promo_group_path %>

app/views/promo_groups/new.html.erb
<h1>New promo_group</h1>

<%= render 'form' %>

<%= link_to 'Back', promo_groups_path %>

app/views/promo_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @promo_group.title %>
</p>

<p>
  <b>Description:</b>
  <%= @promo_group.description %>
</p>

<p>
  <b>Image:</b>
  <%= @promo_group.image %>
</p>

<p>
  <b>Active:</b>
  <%= @promo_group.active %>
</p>


<%= link_to 'Edit', edit_promo_group_path(@promo_group) %> |
<%= link_to 'Back', promo_groups_path %>