config/routes.rb
Valueneeds::Application.routes.draw do

  resources :bottom_banners

  resources :password_resets

  resources :recipes do
    get :recipes_description, :on => :collection
  end

  resources :galleries do
  get :create_gallery, :on => :collection
  end
  resources :wish_lists

  resources :wallet_entries do
    get :my_wallet, :on => :collection
    get :show_wallet, :on => :collection
  end

  resources :notify_me_requests

  resources :delivery_slot_names do
    get :slots_for_mobile, :on => :collection
  end

  resources :pincodes do
    get :users_index, :on => :collection
  end

  resources :system_settings

  resources :product_attributes

  resources :attribute_items

  resources :attributes

  resources :scroll_texts

  resources :specialities

  get "static/contact_us"
  get "static/about_us"
  get "static/faq"
  get "static/privacy_policy"
  get "static/terms_and_conditions"
  get "static/delivery_information"
  get "static/refund_and_return_policy"
  get "static/follow_us"
  get "static/site_map"
  get "static/where_we_deliver"
  get "static/general_information"
  get "static/need_assistance"
  get "static/customer_service"
  get "static/getting_started"
  get "static/vn_offers"
  get "static/coupon_and_vouchers"
  get "static/news_and_events"
  get "static/winners"
  get "static/dataFrom"
  get "static/ccavRequestHandler"
  post "static/payment_response_handler"
  resources :slide_images

  resources :user_sessions

  resources :promo_groups

  resources :product_price_ranges do
    get :load_product_price_range_ids, :on => :collection
    get :get_product_price_range, :on => :collection
  end

  resources :promos do
    get :load_all_promo_ids, :on => :collection
    get :get_promos_by_group, :on => :collection
    get :promo_offers, :on => :collection
    get :promo_complete_details, :on => :collection
    get :get_promo_offer_details, :on => :collection
  end

  resources :delivery_slots do
  get :create_delivery_slots, :on => :collection
  end

  resources :feedbacks

  resources :address_details do
    get :check_out, :on => :collection
    post :create_order_with_previous_address, :on => :collection
    get :get_address_details, :on => :collection
    get :get_delivery_slots, :on => :collection
    get :pay_with_wallet, :on => :collection
    get :confirm_with_wallet, :on => :collection
    post :create_order_with_new_address, :on => :collection
    get :create_order_from_payment_gateway, :on => :collection
  end

  resources :orders do
    get :get_previous_orders, :on => :collection
    get :repeat_order, :on => :collection
    get :invoice_status_details, :on => :collection
    get :order_tracking, :on => :collection
    get :status, :on => :collection
    get :payment_status, :on => :collection
    get :order_status_details, :on => :collection

  end

  resources :users do
    post :update_user_details, :on => :collection
  end

  resources :products do
    get :add_child_form, :on=> :collection
    post :update_category_child, :on => :collection
    get :remove_category, :on => :collection
    post :update_product_location_prices, :on => :collection
    get :add_product_location_price_form, :on => :collection
    get :remove_location_price, :on => :collection
    get :order_online, :on => :collection
    get :add_items_to_cart, :on => :collection
    get :remove_order_item, :on => :collection
    get :show_cart, :on => :collection
    get :login_screen, :on => :collection
    get :remove_order, :on => :collection
    get :update_location, :on => :collection
    get :empty_cart, :on => :collection
    get :get_products, :on => :collection
    get :get_products_by_ids, :on => :collection
    get :load_auto_complete_search_products, :on => :collection
    get :clear_auto_complete_text, :on => :collection
    get :get_main_filtered_products, :on => :collection
    get :show_search_products, :on => :collection
    get :product_details_tab, :on => :collection
    get :product_request, :on => :collection
    get :request_products, :on => :collection
    get :clean_orders, :on => :collection
    get :change_product_selection_quantity, :on => :collection
    get :change_product_tab_selection_quantity, :on => :collection
    get :edit_product, :on => :collection
    get :add_items_to_wish_list, :on => :collection
    get :show_wish_list_products, :on => :collection
    get :remove_wish_list_items, :on => :collection
    get :load_more, :on => :collection
  end

  resources :categories do
    get :get_child_categories, :on => :collection
    get :update_sequence_ids, :on => :collection
    get :change_category_sequence_order, :on => :collection
  end

  resources :locations

  resources :brands do
    get :get_brands_by_ids, :on => :collection
  end
  match 'promo-details/:title/:promo_id', :controller => 'promos', :action => 'promo_complete_details'
  match 'order-products', :controller => 'products', :action => 'order_online'
  match 'login', :controller => 'user_sessions', :action => 'new'
  match 'wallet', :controller => 'wallet_entries', :action => 'my_wallet'
  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'auth/:provider/callback', :to => 'user_sessions#log_in_with_others'
  match 'log_in_with_email', :to => 'user_sessions#log_in_with_email'
  match 'reset-password', :controller => 'password_resets', :action => 'new'

  match 'auth/failure', to: redirect('/')

   root :to => 'products#order_online'

end

app/models/promo.rb
class Promo < ActiveRecord::Base
end

app/helpers/promos_helper.rb
module PromosHelper
  class PromosItem
    attr_accessor :promo_id, :promo_title, :promo_quantity, :offer_type, :offer_product_id, :offer_product_quantity, :discount_percentage, :discount_amount, :order_promo_limit, :savings_amount, :offer_limit_quantity
  end

  class CartOrderItem
    attr_accessor :product, :category, :order_item, :promo
  end

  class CategoryCartLineItem
    attr_accessor :type, :category_id, :category_name, :count, :total_cost, :savings
    def initialize
      @type = 'Category'
      @count = @total_cost = @savings = 0.0
    end
  end

  class ProductCartLineItem
    attr_accessor :type, :product_id, :product_name, :quantity, :original_price, :discounted_price, :effective_price, :sub_total, :savings, :product_attributes, :picture
    def initialize
      @type = 'Product'
      @quantity = @original_price = @discounted_price = @effective_price = @sub_total = @savings = 0
    end
  end

  class PromoCartLineItem
    attr_accessor :type, :promo_id, :description, :savings, :price, :discounted_price, :applied_promo_quantity
    def initialize
      @type = 'Promo'
      @savings = @price = @discounted_price = @applied_promo_quantity = 0
    end
  end

  class OrderItemData
    attr_accessor :product_id, :product_name, :quantity, :original_price, :effective_price, :sub_total, :discounted_price, :order_index, :product_attributes
  end

  class CategoryWiseList
    attr_accessor :cart_order_items, :category, :promo
  end

  class PromoOfferDetail
    attr_accessor :promo_id, :content1, :content2, :content3, :content4, :free_product_id, :all_product_ids
    def initialize
      @free_product_id = nil
    end
  end

  class PromoBasketDetail
    attr_accessor :name, :content1, :content2, :content3, :content4, :content5
  end

  def get_all_promo_types
    ['On Order Value','On Product','On Product Range']
  end

  def get_promo_offer_types
    ['Discount Amount','Discount Percentage','Add Other Product', 'Add Same Product']
  end

  def get_cart_by_category_level(session_order_items)
    list_of_categories = Array.new
    order_items = get_order_items_by_order(session_order_items)
    items_lists = get_cart_list_category_group_wise(order_items)
    if !items_lists.blank?
       items_lists.each do|list|
         category_wise_list = CategoryWiseList.new
         category_wise_list.cart_order_items = list
         list.each_with_index do|order_item,index|
            break if index > 0
            category_wise_list.category = order_item.category
         end
=begin
         promo_range = Promo.find_by_product_range_id(category_wise_list.category.id)
         if !promo_range.blank?
           promo_item = is_category_has_promo_range(promo_range,list)
           if !promo_item.blank?
             category_wise_list.promo = promo_item
           end
         end
=end
         list_of_categories << category_wise_list
       end
    end
   list_of_categories
  end

  def get_cart_list_category_group_wise(order_items)
     list_items = cart_temp_list(order_items)
     #list_items = list_items.sort! { |a, b| a.category.id <=> b.category.id }
     objects_lists = Array.new
     list_items.each_with_index do |order_item|
        group = is_category_in_list(objects_lists,order_item.category)
        list = Array.new
        if !group.blank?
        list = group
        list << order_item
        else
        objects_lists << list
        list << order_item
        end
     end
    objects_lists
  end


  def is_category_in_list(objects_lists, category)
      result = nil
      if !objects_lists.blank?
         objects_lists.each do |list|
           if !list.blank?
            list.each do |order_item|
                  if order_item.category.id == category.id
                       result = list
                  end
              end
           end
         end
      end
     result
  end

  def cart_temp_list(order_items)
    objects_lists = Array.new
        order_items.each_with_index do |order_item, index|
            product = Product.find_by_id(order_item.item_id)
            product_category = ProductCategory.find_by_product_id(product.id)
            category = !product_category.blank? ? Category.find_by_id(product_category.category_id) : Category.find_by_id(541)
            category = get_parent_level_category(category)
            order_item_obj = CartOrderItem.new
            order_item_obj.product = product
            order_item_obj.category = category
            order_item_data_obj = OrderItemData.new
            order_item_data_obj.product_id = order_item.item_id
            order_item_data_obj.product_name = product.name
            order_item_data_obj.quantity = order_item.quantity
            order_item_data_obj.original_price = order_item.price
            order_item_data_obj.product_attributes = order_item.product_attributes if !order_item.product_attributes.blank?
            order_item_data_obj.effective_price = order_item.price - get_discount_product_price(product)
            order_item_data_obj.order_index = index
            order_item_data_obj.sub_total = (order_item.quantity.to_i*order_item_data_obj.effective_price.to_d).round(2)
            #............promo calculations
            promo = is_item_has_promo(order_item_data_obj)
             if !promo.blank?
               order_item_obj.promo = promo
               order_item_data_obj.sub_total = (order_item_data_obj.sub_total - promo.savings_amount).round(2) if promo.offer_type != 'Add Other Product' && promo.offer_type != 'Add Same Product'
               order_item_data_obj.effective_price = (order_item_data_obj.sub_total/order_item_data_obj.quantity.to_i).round(2)
             end
           order_item_obj.order_item = order_item_data_obj
        objects_lists << order_item_obj
        end
    objects_lists
  end

  def get_parent_level_category(category)
      result = category
      if !category.parent_id.blank?
         parent_category = Category.find_by_id(category.parent_id)
         result = get_parent_level_category(parent_category) if !parent_category.blank?
      end
    result
  end

  def get_order_items_by_order(order_items)
    list_of_order_items = Array.new
    order_items.each do |order_item|
      product_category = ProductCategory.find_by_product_id(order_item.item_id)
      category = !product_category.blank? ? Category.find_by_id(product_category.category_id) : Category.find_by_id(541)
      category_id = get_parent_level_category(category).id
      list_of_order_items << [order_item, category_id]
    end
    list_of_order_items.sort! { |a, b| a[1] <=> b[1] }
    list_of_order_items.collect { |order_item| order_item[0] }
  end

  def get_cart_line_items(session_order_items)
    objects_lists = Array.new
    last_category_item = nil
    order_items = get_order_items_by_order(session_order_items)
    order_items.each_with_index do |order_item, index|
      product = Product.find_by_id(order_item.item_id)
      product_category = ProductCategory.find_by_product_id(product.id)
      product_category_id = !product_category.blank? ? product_category.category_id : 541
      category =  get_parent_level_category(Category.find_by_id(product_category_id))
      if last_category_item.nil? || last_category_item.category_id != category.id
        last_category_item = CategoryCartLineItem.new
        last_category_item.category_id = category.id
        last_category_item.category_name = category.name
        objects_lists << last_category_item
      end
      last_category_item.count += 1
      product_line_item = ProductCartLineItem.new
      product_line_item.product_id = product.id
      product_line_item.product_name = product.name
      product_line_item.picture = root_url+'product/'+product.picture if !product.picture.blank?
      product_line_item.quantity = order_item.quantity
      product_line_item.original_price = order_item.price
      product_line_item.product_attributes = order_item.product_attributes if !order_item.product_attributes.blank?
      product_line_item.effective_price = product.price - get_discount_product_price(product)
      product_line_item.sub_total = (order_item.quantity.to_i*product_line_item.effective_price.to_d).round(2)
      product_line_item.savings = get_discount_product_price(product)*product_line_item.quantity.to_i
      objects_lists << product_line_item
      ##............promo calculations
      promo = is_item_has_promo(product_line_item)
      if !promo.blank?
        promo_line_item = PromoCartLineItem.new
        promo_line_item.promo_id = promo.promo_id
        promo_line_item.description = promo.promo_title
        promo_line_item.savings = promo.savings_amount
        promo_line_item.applied_promo_quantity = promo.offer_limit_quantity
        if promo.offer_type == 'Discount Percentage' || promo.offer_type == 'Discount Amount'
          product_line_item.sub_total = (product_line_item.sub_total - promo.savings_amount).round(2)
          product_line_item.effective_price = (product_line_item.sub_total/product_line_item.quantity.to_i).round(2)
        end
        objects_lists << promo_line_item
      end
      last_category_item.total_cost += product_line_item.sub_total
    end
    objects_lists
  end


  def is_item_has_promo(order_item)
    promo = Promo.find_by_product_id(order_item.product_id)
    promo_item = PromosItem.new
    if !promo.blank? && order_item.quantity.to_i >= promo.product_quantity.to_i
          promo_item.promo_id = promo.id
          promo_item.promo_title = promo.promo_title
          promo_item.offer_type = promo.offer_type
          promo_item.offer_limit_quantity = (order_item.quantity.to_i/promo.product_quantity.to_i)
          promo_item.offer_limit_quantity = promo.order_promo_limit if (promo_item.offer_limit_quantity > promo.order_promo_limit)
          if promo_item.offer_type == 'Discount Percentage'
             promo_item.discount_percentage = promo.discount_percent

app/views/promos/_form.html.erb
<%= form_for(@promo) do |f| %>
  <% if @promo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@promo.errors.count, "error") %> prohibited this promo from being saved:</h2>

      <ul>
      <% @promo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
     <%= f.label :promo_group_id %><br />
     <%= f.select :promo_group_id, options_for_select(get_promo_groups, @promo.promo_group_id) %>
  </div>

  <div class="field">
    <%= f.label :promo_type %><br />
    <%= f.select :promo_type, options_for_select(get_all_promo_types, @promo.promo_type) %>
  </div>
  <div class="field">
    <%= f.label :promo_title %><br />
    <%= f.text_field :promo_title %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :product_quantity %><br />
    <%= f.text_field :product_quantity %>
  </div>
  <div class="field">
    <%= f.label :product_range_id %><br />
    <%= f.text_field :product_range_id %>
  </div>
  <div class="field">
    <%= f.label :order_value %><br />
    <%= f.number_field :order_value %>
  </div>
  <div class="field">
    <%= f.label :valid_from %><br />
    <%= f.datetime_select :valid_from %>
  </div>
  <div class="field">
    <%= f.label :valid_till %><br />
    <%= f.datetime_select :valid_till %>
  </div>
  <div class="field">
    <%= f.label :order_promo_limit %><br />
    <%= f.number_field :order_promo_limit %>
  </div>
  <div class="field">
    <%= f.label :customer_promo_limit %><br />
    <%= f.number_field :customer_promo_limit %>
  </div>
  <div class="field">
    <%= f.label :offer_type %><br />
    <%= f.select :offer_type, options_for_select(get_promo_offer_types, @promo.offer_type) %>
  </div>
  <div class="field">
    <%= f.label :discount_amount %><br />
    <%= f.number_field :discount_amount %>
  </div>
  <div class="field">
    <%= f.label :discount_percent %><br />
    <%= f.number_field :discount_percent %>
  </div>
  <div class="field">
    <%= f.label :offer_product_id %><br />
    <%= f.number_field :offer_product_id %>
  </div>
  <div class="field">
    <%= f.label :offer_other_product_quantity %><br />
    <%= f.text_field :offer_other_product_quantity %>
  </div>
  <div class="field">
    <%= f.label :offer_same_product_quantity %><br />
    <%= f.text_field :offer_same_product_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/promos/_promo_add_other_product.html.erb
<% promo = Promo.find_by_id(promo_cart_line_item.promo_id) %>
<tr>
  <td>
    <div class="img-view-basket-promo-arrows">
                                        <span class="uiv2-grid-offer-applied icon icon-promo-green-small">
                                       <span style="padding-left: 20px;"> <a href="#" style="text-decoration: none">
                                         PROMO APPLIED :
                                        <span><%= promo.promo_title %></span></a></span></span></div>
  </td>
  <% if promo.offer_type == "Add Other Product" || promo.offer_type == "Add Same Product" %>
      <% offer_product = !promo.offer_product_id.blank? ? Product.find_by_id(promo.offer_product_id) : Product.find_by_id(order_item.product_id) %>
      <td>
        <div style="text-align: center">
          <%= promo_cart_line_item.applied_promo_quantity %>
        </div>
      </td>
      <td style="text-align: center">
        <div style="color: green"> Free</div>
        <div class="uiv2-unit-price_Rate"><%= offer_product.price %></div>
      </td>
      <td></td>
      <td>
        <div style="color: #ff0000;font-weight: bold;text-align: center">
          <%= promo_cart_line_item.savings %>
        </div>
      </td>
  <% end %>

  <% if promo.offer_type == "Discount Amount" || promo.offer_type == "Discount Percentage"%>
      <td>
        <div style="text-align: center">
          <%= promo_cart_line_item.applied_promo_quantity %>
        </div>
      </td>
      <td style="text-align: center">
        <div> <%= order_item.discounted_price %> </div>
        <div class="uiv2-unit-price_Rate"><%= order_item.original_price.to_d %></div>
      </td>
      <td></td>
      <td>
        <div style="color: #ff0000;font-weight: bold;text-align: center">
          <%= promo_cart_line_item.savings %>
        </div>
      </td>
  <% end %>
</tr>

app/views/promos/_promo_basket_details.html.erb
<% basket =get_promo_products_details(promo) %>
<div class="uiv2-div100 uiv2-pro-sel-tab">
  <div class="uiv2-div-w-200 uiv2-mar-l-20 uiv2-mar-t-10 uiv2-border-right-dotted">
    <div class="uiv2-div90 uiv2-mar-t-10 uiv2-sub-content-3"><%= basket.name %> </div>
    <div class="uiv2-div90 uiv2-mar-t-10 uiv2-sub-content-2-1"><%= basket.content1 %></div>
                         <span class="uiv2-div90 uiv2-mar-t-10 uiv2-sub-content-sm">
                             <%= basket.content2 %>
                         </span>
  </div>
</div>
<div class="uiv2-div100">
  <div class="uiv2-used-promos">
    <span class="uiv2-div100 uiv2-sub-content-2-1 uiv2-pad-r-10"><%= basket.content3 %><br/><%= basket.content4 %></span>
  </div>
  <div class="uiv2-mar-t-15 uiv2-left uiv2-sub-content-2-1 promoMsgInfo">
    <div class="promo-msg-info-dynamic"> <%= basket.content2 %> </div>
  </div>
</div>

app/views/promos/_promo_min_banner.html.erb
<div class="uiv2-promo-nav-menu uiv2-div100">
  <div class="uiv2-offers uiv2-mar-l-20" style="padding-top: 15px;">
     <span class="uiv2-style1">
               Value Need
          </span><span class="uiv2-style2">
               OFFERS
          </span>
  </div>
  <ul style="float:left; padding: 10px">
    <li><a href="#">Discounts</a></li>
    <!--<li><a href="/promos/promo_offers">Promotions</a></li>-->
    <li><a href="#">Bundle Packs</a></li>
  </ul>
</div>
<div style="clear: both"></div>

app/views/promos/_promo_show_offers.html.erb
<p style="font-size: 14px;">Amazing <%= Date::MONTHNAMES[Date.today.month] %> Offers</p>
<div>
     <ul style="list-style: none;padding: 0px;margin: 0 0 0 5px;">
       <% @promos = Promo.find(:all, :conditions => ['valid_from <= ? and valid_till >= ?', Time.now, Time.now]) %>
       <% @promos.each do |promo| %>
            <li style="padding: 4px 3px 2px 4px"><a href="/promo-details/<%= offer_rename(promo.promo_title) %>/<%= promo.id %>" style="text-decoration: none;padding: 4px 3px 2px 4px" id="promo_offer_<%= promo.id %>">- <%= promo.promo_title %></a></li>
       <% end %>
     </ul>
</div>

app/views/promos/edit.html.erb
<h1>Editing promo</h1>

<%= render 'form' %>

<%= link_to 'Show', @promo %> |
<%= link_to 'Back', promos_path %>

app/views/promos/index.html.erb
<h1>Listing promos</h1>

<table>
  <tr>
    <th>Promo type</th>
    <th>Promo title</th>
    <th>Product</th>
    <th>Product quantity</th>
    <th>Product range tag</th>
    <th>Order value</th>
    <th>Valid from</th>
    <th>Valid till</th>
    <th>Order promo limit</th>
    <th>Customer promo limit</th>
    <th>Offer type</th>
    <th>Discount amount</th>
    <th>Discount percent</th>
    <th>Offer product</th>
    <th>Offer other product quantity</th>
    <th>Offer same product quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @promos.each do |promo| %>
  <tr>
    <td><%= promo.promo_type %></td>
    <td><%= promo.promo_title %></td>
    <td><%= promo.product_id %></td>
    <td><%= promo.product_quantity %></td>
    <td><%= promo.product_range_id %></td>
    <td><%= promo.order_value %></td>
    <td><%= promo.valid_from %></td>
    <td><%= promo.valid_till %></td>
    <td><%= promo.order_promo_limit %></td>
    <td><%= promo.customer_promo_limit %></td>
    <td><%= promo.offer_type %></td>
    <td><%= promo.discount_amount %></td>
    <td><%= promo.discount_percent %></td>
    <td><%= promo.offer_product_id %></td>
    <td><%= promo.offer_other_product_quantity %></td>
    <td><%= promo.offer_same_product_quantity %></td>
    <td><%= link_to 'Show', promo %></td>
    <td><%= link_to 'Edit', edit_promo_path(promo) %></td>
    <td><%= link_to 'Destroy', promo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Promo', new_promo_path %>

app/views/promos/new.html.erb
<h1>New promo</h1>

<%= render 'form' %>

<%= link_to 'Back', promos_path %>

app/views/promos/promo_offers.html.erb
<div align="center">
  <div style="width: 99%;margin-right: 8px;padding-top: 20px;">
    <%= render :partial => 'promo_min_banner' %>
   <table width="100%" cellspacing="10">
      <tr>
        <% @promos.each_with_index do |promo, index| %>
            <% promo_offer_details = get_promo_details(promo) %>
            <% product = Product.find(promo_offer_details.all_product_ids[0]) %>
           <td>
             <a href="/promo-details/<%= offer_rename(promo.promo_title) %>/<%= promo.id %>"> <div class="promo-box box-gradiant">

                <div class="uiv2-div65"><span class="uiv2-mar-t-16 uiv2-mar-l-15 uiv2-div100 style1" style="font: 14px 'MyriadFont';color:#A7A9AC ;">
                     <%= promo_offer_details.content1 %>
                     </span><span class="uiv2-mar-t-16 uiv2-mar-l-15 uiv2-div100 style2" style="font: 16px 'MyriadFont' ;color:#58595B ;">
			                <%= promo_offer_details.content2 %> &amp;
			             </span>
                          <span class="uiv2-mar-t-16 uiv2-mar-l-15 uiv2-div100 style3" style="font: 20px 'MyriadFont';color: #414042;width:135%;">
                           <%= promo_offer_details.content3 %>
			             </span>
                </div>

                <div class="uiv2-div-promo">
                  <span class="uiv2-mar-t-16">
                    <%= image_tag("/product/#{product.picture}", :width => '75px', :height => '75px', :style => "margin-left:10px;") %>
                  </span>
                </div>
              </div></a>
            </td>
            <% if (index+1)%3 ==0 %>
                </tr>
                <tr>
            <% end %>
        <% end %>
        </tr>
        </table>
  </div>
</div>

app/views/promos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Promo type:</b>
  <%= @promo.promo_type %>
</p>

<p>
  <b>Promo title:</b>
  <%= @promo.promo_title %>
</p>

<p>
  <b>Product:</b>
  <%= @promo.product_id %>
</p>

<p>
  <b>Product quantity:</b>
  <%= @promo.product_quantity %>
</p>

<p>
  <b>Product range tag:</b>
  <%= @promo.product_range_id %>
</p>

<p>
  <b>Order value:</b>
  <%= @promo.order_value %>
</p>

<p>
  <b>Valid from:</b>
  <%= @promo.valid_from %>
</p>

<p>
  <b>Valid till:</b>
  <%= @promo.valid_till %>
</p>

<p>
  <b>Order promo limit:</b>
  <%= @promo.order_promo_limit %>
</p>

<p>
  <b>Customer promo limit:</b>
  <%= @promo.customer_promo_limit %>
</p>

<p>
  <b>Offer type:</b>
  <%= @promo.offer_type %>
</p>

<p>
  <b>Discount amount:</b>
  <%= @promo.discount_amount %>
</p>

<p>
  <b>Discount percent:</b>
  <%= @promo.discount_percent %>
</p>

<p>
  <b>Offer product:</b>
  <%= @promo.offer_product_id %>
</p>

<p>
  <b>Offer other product quantity:</b>
  <%= @promo.offer_other_product_quantity %>
</p>

<p>
  <b>Offer same product quantity:</b>
  <%= @promo.offer_same_product_quantity %>
</p>


<%= link_to 'Edit', edit_promo_path(@promo) %> |
<%= link_to 'Back', promos_path %>