config/routes.rb
Valueneeds::Application.routes.draw do

  resources :bottom_banners

  resources :password_resets

  resources :recipes do
    get :recipes_description, :on => :collection
  end

  resources :galleries do
  get :create_gallery, :on => :collection
  end
  resources :wish_lists

  resources :wallet_entries do
    get :my_wallet, :on => :collection
    get :show_wallet, :on => :collection
  end

  resources :notify_me_requests

  resources :delivery_slot_names do
    get :slots_for_mobile, :on => :collection
  end

  resources :pincodes do
    get :users_index, :on => :collection
  end

  resources :system_settings

  resources :product_attributes

  resources :attribute_items

  resources :attributes

  resources :scroll_texts

  resources :specialities

  get "static/contact_us"
  get "static/about_us"
  get "static/faq"
  get "static/privacy_policy"
  get "static/terms_and_conditions"
  get "static/delivery_information"
  get "static/refund_and_return_policy"
  get "static/follow_us"
  get "static/site_map"
  get "static/where_we_deliver"
  get "static/general_information"
  get "static/need_assistance"
  get "static/customer_service"
  get "static/getting_started"
  get "static/vn_offers"
  get "static/coupon_and_vouchers"
  get "static/news_and_events"
  get "static/winners"
  get "static/dataFrom"
  get "static/ccavRequestHandler"
  post "static/payment_response_handler"
  resources :slide_images

  resources :user_sessions

  resources :promo_groups

  resources :product_price_ranges do
    get :load_product_price_range_ids, :on => :collection
    get :get_product_price_range, :on => :collection
  end

  resources :promos do
    get :load_all_promo_ids, :on => :collection
    get :get_promos_by_group, :on => :collection
    get :promo_offers, :on => :collection
    get :promo_complete_details, :on => :collection
    get :get_promo_offer_details, :on => :collection
  end

  resources :delivery_slots do
  get :create_delivery_slots, :on => :collection
  end

  resources :feedbacks

  resources :address_details do
    get :check_out, :on => :collection
    post :create_order_with_previous_address, :on => :collection
    get :get_address_details, :on => :collection
    get :get_delivery_slots, :on => :collection
    get :pay_with_wallet, :on => :collection
    get :confirm_with_wallet, :on => :collection
    post :create_order_with_new_address, :on => :collection
    get :create_order_from_payment_gateway, :on => :collection
  end

  resources :orders do
    get :get_previous_orders, :on => :collection
    get :repeat_order, :on => :collection
    get :invoice_status_details, :on => :collection
    get :order_tracking, :on => :collection
    get :status, :on => :collection
    get :payment_status, :on => :collection
    get :order_status_details, :on => :collection

  end

  resources :users do
    post :update_user_details, :on => :collection
  end

  resources :products do
    get :add_child_form, :on=> :collection
    post :update_category_child, :on => :collection
    get :remove_category, :on => :collection
    post :update_product_location_prices, :on => :collection
    get :add_product_location_price_form, :on => :collection
    get :remove_location_price, :on => :collection
    get :order_online, :on => :collection
    get :add_items_to_cart, :on => :collection
    get :remove_order_item, :on => :collection
    get :show_cart, :on => :collection
    get :login_screen, :on => :collection
    get :remove_order, :on => :collection
    get :update_location, :on => :collection
    get :empty_cart, :on => :collection
    get :get_products, :on => :collection
    get :get_products_by_ids, :on => :collection
    get :load_auto_complete_search_products, :on => :collection
    get :clear_auto_complete_text, :on => :collection
    get :get_main_filtered_products, :on => :collection
    get :show_search_products, :on => :collection
    get :product_details_tab, :on => :collection
    get :product_request, :on => :collection
    get :request_products, :on => :collection
    get :clean_orders, :on => :collection
    get :change_product_selection_quantity, :on => :collection
    get :change_product_tab_selection_quantity, :on => :collection
    get :edit_product, :on => :collection
    get :add_items_to_wish_list, :on => :collection
    get :show_wish_list_products, :on => :collection
    get :remove_wish_list_items, :on => :collection
    get :load_more, :on => :collection
  end

  resources :categories do
    get :get_child_categories, :on => :collection
    get :update_sequence_ids, :on => :collection
    get :change_category_sequence_order, :on => :collection
  end

  resources :locations

  resources :brands do
    get :get_brands_by_ids, :on => :collection
  end
  match 'promo-details/:title/:promo_id', :controller => 'promos', :action => 'promo_complete_details'
  match 'order-products', :controller => 'products', :action => 'order_online'
  match 'login', :controller => 'user_sessions', :action => 'new'
  match 'wallet', :controller => 'wallet_entries', :action => 'my_wallet'
  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'auth/:provider/callback', :to => 'user_sessions#log_in_with_others'
  match 'log_in_with_email', :to => 'user_sessions#log_in_with_email'
  match 'reset-password', :controller => 'password_resets', :action => 'new'

  match 'auth/failure', to: redirect('/')

   root :to => 'products#order_online'

end

app/models/product_price_range.rb
class ProductPriceRange < ActiveRecord::Base
end

app/controllers/product_price_ranges_controller.rb
class ProductPriceRangesController < ApplicationController
  filter_resource_access
  filter_access_to :get_product_price_range, :attribute_check => false
  filter_access_to :load_product_price_range_ids, :attribute_check => false
  # GET /product_price_ranges
  # GET /product_price_ranges.json
  def index
    @product_price_ranges = ProductPriceRange.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @product_price_ranges }
    end
  end

  # GET /product_price_ranges/1
  # GET /product_price_ranges/1.json
  def show
    @product_price_range = ProductPriceRange.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product_price_range }
    end
  end

  # GET /product_price_ranges/new
  # GET /product_price_ranges/new.json
  def new
    @product_price_range = ProductPriceRange.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product_price_range }
    end
  end

  # GET /product_price_ranges/1/edit
  def edit
    @product_price_range = ProductPriceRange.find(params[:id])
  end

  # POST /product_price_ranges
  # POST /product_price_ranges.json
  def create
    @product_price_range = ProductPriceRange.new(params[:product_price_range])

    respond_to do |format|
      if @product_price_range.save
        format.html { redirect_to @product_price_range, notice: 'Product price range was successfully created.' }
        format.json { render json: @product_price_range, status: :created, location: @product_price_range }
      else
        format.html { render action: "new" }
        format.json { render json: @product_price_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /product_price_ranges/1
  # PUT /product_price_ranges/1.json
  def update
    @product_price_range = ProductPriceRange.find(params[:id])

    respond_to do |format|
      if @product_price_range.update_attributes(params[:product_price_range])
        format.html { redirect_to @product_price_range, notice: 'Product price range was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @product_price_range.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_price_ranges/1
  # DELETE /product_price_ranges/1.json
  def destroy
    @product_price_range = ProductPriceRange.find(params[:id])
    @product_price_range.destroy

    respond_to do |format|
      format.html { redirect_to product_price_ranges_url }
      format.json { head :ok }
    end
  end

  def load_product_price_range_ids
    @product_price_ranges = ProductPriceRange.all
    @product_price_ranges.each do |product_price_range|
      Product.where('price >= ? and price <= ?', product_price_range.start_price, product_price_range.end_price).update_all(product_price_range_id: product_price_range.id)
    end
    redirect_to '/product_price_ranges'
  end

  def get_product_price_range
    @product_price_ranges = ProductPriceRange.find(:all, :conditions => ['id in (?)', params[:price_range_ids].split(',')])
    respond_to do |format|
      format.json { render json: @product_price_ranges}
    end
  end
end

app/helpers/product_price_ranges_helper.rb
module ProductPriceRangesHelper
end

app/views/product_price_ranges/_form.html.erb
<%= form_for(@product_price_range) do |f| %>
  <% if @product_price_range.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_price_range.errors.count, "error") %> prohibited this product_price_range from being saved:</h2>

      <ul>
      <% @product_price_range.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_price %><br />
    <%= f.text_field :start_price %>
  </div>
  <div class="field">
    <%= f.label :end_price %><br />
    <%= f.text_field :end_price %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_price_ranges/edit.html.erb
<h1>Editing product_price_range</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_price_range %> |
<%= link_to 'Back', product_price_ranges_path %>

app/views/product_price_ranges/index.html.erb
<h1>Listing product_price_ranges</h1>

<table>
  <tr>
    <th>Start price</th>
    <th>End price</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @product_price_ranges.each do |product_price_range| %>
  <tr>
    <td><%= product_price_range.start_price %></td>
    <td><%= product_price_range.end_price %></td>
    <td><%= product_price_range.description %></td>
    <td><%= link_to 'Show', product_price_range %></td>
    <td><%= link_to 'Edit', edit_product_price_range_path(product_price_range) %></td>
    <td><%= link_to 'Destroy', product_price_range, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product price range', new_product_price_range_path %>

app/views/product_price_ranges/new.html.erb
<h1>New product_price_range</h1>

<%= render 'form' %>

<%= link_to 'Back', product_price_ranges_path %>

app/views/product_price_ranges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Start price:</b>
  <%= @product_price_range.start_price %>
</p>

<p>
  <b>End price:</b>
  <%= @product_price_range.end_price %>
</p>

<p>
  <b>Description:</b>
  <%= @product_price_range.description %>
</p>


<%= link_to 'Edit', edit_product_price_range_path(@product_price_range) %> |
<%= link_to 'Back', product_price_ranges_path %>