config/routes.rb
Valueneeds::Application.routes.draw do

  resources :bottom_banners

  resources :password_resets

  resources :recipes do
    get :recipes_description, :on => :collection
  end

  resources :galleries do
  get :create_gallery, :on => :collection
  end
  resources :wish_lists

  resources :wallet_entries do
    get :my_wallet, :on => :collection
    get :show_wallet, :on => :collection
  end

  resources :notify_me_requests

  resources :delivery_slot_names do
    get :slots_for_mobile, :on => :collection
  end

  resources :pincodes do
    get :users_index, :on => :collection
  end

  resources :system_settings

  resources :product_attributes

  resources :attribute_items

  resources :attributes

  resources :scroll_texts

  resources :specialities

  get "static/contact_us"
  get "static/about_us"
  get "static/faq"
  get "static/privacy_policy"
  get "static/terms_and_conditions"
  get "static/delivery_information"
  get "static/refund_and_return_policy"
  get "static/follow_us"
  get "static/site_map"
  get "static/where_we_deliver"
  get "static/general_information"
  get "static/need_assistance"
  get "static/customer_service"
  get "static/getting_started"
  get "static/vn_offers"
  get "static/coupon_and_vouchers"
  get "static/news_and_events"
  get "static/winners"
  get "static/dataFrom"
  get "static/ccavRequestHandler"
  post "static/payment_response_handler"
  resources :slide_images

  resources :user_sessions

  resources :promo_groups

  resources :product_price_ranges do
    get :load_product_price_range_ids, :on => :collection
    get :get_product_price_range, :on => :collection
  end

  resources :promos do
    get :load_all_promo_ids, :on => :collection
    get :get_promos_by_group, :on => :collection
    get :promo_offers, :on => :collection
    get :promo_complete_details, :on => :collection
    get :get_promo_offer_details, :on => :collection
  end

  resources :delivery_slots do
  get :create_delivery_slots, :on => :collection
  end

  resources :feedbacks

  resources :address_details do
    get :check_out, :on => :collection
    post :create_order_with_previous_address, :on => :collection
    get :get_address_details, :on => :collection
    get :get_delivery_slots, :on => :collection
    get :pay_with_wallet, :on => :collection
    get :confirm_with_wallet, :on => :collection
    post :create_order_with_new_address, :on => :collection
    get :create_order_from_payment_gateway, :on => :collection
  end

  resources :orders do
    get :get_previous_orders, :on => :collection
    get :repeat_order, :on => :collection
    get :invoice_status_details, :on => :collection
    get :order_tracking, :on => :collection
    get :status, :on => :collection
    get :payment_status, :on => :collection
    get :order_status_details, :on => :collection

  end

  resources :users do
    post :update_user_details, :on => :collection
  end

  resources :products do
    get :add_child_form, :on=> :collection
    post :update_category_child, :on => :collection
    get :remove_category, :on => :collection
    post :update_product_location_prices, :on => :collection
    get :add_product_location_price_form, :on => :collection
    get :remove_location_price, :on => :collection
    get :order_online, :on => :collection
    get :add_items_to_cart, :on => :collection
    get :remove_order_item, :on => :collection
    get :show_cart, :on => :collection
    get :login_screen, :on => :collection
    get :remove_order, :on => :collection
    get :update_location, :on => :collection
    get :empty_cart, :on => :collection
    get :get_products, :on => :collection
    get :get_products_by_ids, :on => :collection
    get :load_auto_complete_search_products, :on => :collection
    get :clear_auto_complete_text, :on => :collection
    get :get_main_filtered_products, :on => :collection
    get :show_search_products, :on => :collection
    get :product_details_tab, :on => :collection
    get :product_request, :on => :collection
    get :request_products, :on => :collection
    get :clean_orders, :on => :collection
    get :change_product_selection_quantity, :on => :collection
    get :change_product_tab_selection_quantity, :on => :collection
    get :edit_product, :on => :collection
    get :add_items_to_wish_list, :on => :collection
    get :show_wish_list_products, :on => :collection
    get :remove_wish_list_items, :on => :collection
    get :load_more, :on => :collection
  end

  resources :categories do
    get :get_child_categories, :on => :collection
    get :update_sequence_ids, :on => :collection
    get :change_category_sequence_order, :on => :collection
  end

  resources :locations

  resources :brands do
    get :get_brands_by_ids, :on => :collection
  end
  match 'promo-details/:title/:promo_id', :controller => 'promos', :action => 'promo_complete_details'
  match 'order-products', :controller => 'products', :action => 'order_online'
  match 'login', :controller => 'user_sessions', :action => 'new'
  match 'wallet', :controller => 'wallet_entries', :action => 'my_wallet'
  match 'logout', :controller => 'user_sessions', :action => 'destroy'
  match 'auth/:provider/callback', :to => 'user_sessions#log_in_with_others'
  match 'log_in_with_email', :to => 'user_sessions#log_in_with_email'
  match 'reset-password', :controller => 'password_resets', :action => 'new'

  match 'auth/failure', to: redirect('/')

   root :to => 'products#order_online'

end

app/models/address_detail.rb
class AddressDetail < ActiveRecord::Base
  validates_presence_of :first_name, :last_name, :contact_number, :house_no, :area, :pincode, :city, :land_mark

end

app/controllers/address_details_controller.rb
class AddressDetailsController < ApplicationController
  include ApplicationHelper::SessionConstants
  include PromosHelper
  include ApplicationHelper

  filter_resource_access
  filter_access_to :check_out, :attribute_check => false
  filter_access_to :create_order_with_previous_address, :attribute_check => false
  filter_access_to :get_address_details, :attribute_check => false
  filter_access_to :get_delivery_slots, :attribute_check => false
  filter_access_to :create_order_with_new_address, :attribute_check => false
  filter_access_to :pay_with_wallet, :attribute_check => false
  filter_access_to :confirm_with_wallet, :attribute_check => false
  filter_access_to :create_order_from_payment_gateway, :attribute_check => false

  # GET /address_details
  # GET /address_details.json
  def index
    @address_details = AddressDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @address_details }
    end
  end

  # GET /address_details/1
  # GET /address_details/1.json
  def show
    @address_detail = AddressDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @address_detail }
    end
  end

  # GET /address_details/new
  # GET /address_details/new.json
  def new
    @address_detail = AddressDetail.new
    if current_user.blank?
      @user_session = UserSession.new
      @user = User.new
    end
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @address_detail }
    end
  end

  # GET /address_details/1/edit
  def edit
    @address_detail = AddressDetail.find(params[:id])
  end

  # POST /address_details
  # POST /address_details.json
  def create
    @address_detail = AddressDetail.new(params[:address_detail])

    pincode = Pincode.find_by_code(@address_detail.pincode)

    is_valid_pincode = !pincode.blank? && pincode.active

    @address_detail.errors['pincode_error'] = 'Currently we do not deliver at this pin code' if !is_valid_pincode

    if !current_user.blank?
      @address_detail.buyer_id = current_user.id
    end
    respond_to do |format|
      if is_valid_pincode && @address_detail.save
        format.html { redirect_to '/address_details/check_out', :notice => 'New address is successfully added.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @address_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /address_details/1
  # PUT /address_details/1.json
  def update
    @address_detail = AddressDetail.find(params[:id])

    respond_to do |format|
      if @address_detail.update_attributes(params[:address_detail])
        format.html { redirect_to @address_detail, notice: 'Address detail was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @address_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_details/1
  # DELETE /address_details/1.json
  def destroy
    @address_detail = AddressDetail.find(params[:id])
    @address_detail.destroy

    respond_to do |format|
      format.html { redirect_to address_details_url }
      format.json { head :ok }
    end
  end

  def check_out
    @address_details = AddressDetail.new
    @address_details = AddressDetail.find(:all, :conditions => ["buyer_id = ?", current_user.id], :order => "created_at desc", :limit => 3) if !current_user.blank?
    @delivery_slots = DeliverySlotName.get_active_slots
    @cart_items = !current_user.blank? ? CartItem.find_all_by_user_id(current_user.id) : CartItem.find_all_by_session_id(session[SESSION_ID])
    @needs_payment = needs_payment?(@cart_items)
    if @cart_items.blank?
      redirect_to '/products/show_cart'
    else
      if current_user.blank? || @address_details.size < 1
        session['REDIRECT_URL'] = '/address_details/check_out'
        redirect_to '/address_details/new'
      end
    end
  end

  def create_order_with_previous_address
    redirect_url = ''
    valid_coupon = is_valid_coupon(params[:coupon_code], 'VN001')
    if params[:coupon_code].blank? || valid_coupon
      coupon_code = params[:coupon_code] if valid_coupon
      @cart_items = CartItem.find_all_by_user_id(current_user.id)
      if @cart_items.blank?
        redirect_url='/products/show_cart'
        notice = ''
      else
        total_price = get_total_charges_with_out_delivery_charges
        if params[:commit].eql?('Apply Coupon')
            coupon_discount = get_discount_on_coupon(total_price)
            redirect_url="/address_details/check_out?coupon_code=#{params[:coupon_code]}"
        elsif params[:commit].eql?('Pay Online')
          @online_payment = OnlinePayment.new
          random_id = UUIDTools::UUID.random_create.to_s.delete '-'
          random_id[0..2]=''
          @online_payment.merchant_transaction_id = random_id
          if !coupon_code.blank?
            @online_payment.coupon_code=coupon_code

            @online_payment.coupon_discount = get_discount_on_coupon(total_price)
            grand_total=total_price-@online_payment.coupon_discount
            delivery_charges = get_delivery_charges(total_price)
            @online_payment.transaction_amount = (grand_total+delivery_charges).round(2)
          else
            @online_payment.transaction_amount = get_total_amount
          end
          @online_payment.address_id = params[:address_id]
          @online_payment.payment_status = 'Created'
          @online_payment.save
          @cart_items.each do |cart_item|
            cart_item.update_attribute(:merchant_transaction_id, @online_payment.merchant_transaction_id);
          end
          redirect_url="/address_details/pay_with_wallet?mti=#{@online_payment.merchant_transaction_id}"
        else
          @needs_payment = needs_payment?(@cart_items)
          if !@needs_payment
            @address_detail = AddressDetail.find_by_id(params[:address_id])
            payment_mode = 'Cash'
            payment_mode = 'SodexHo_TicketRestaurant' if params[:commit].eql?('Pay With Sodexo/Ticket Restaurant')
            create_order(payment_mode, coupon_code)
            redirect_url="/orders/invoice_status_details?id=#{@order.id}"
            notice = 'Your Order Is Taken We will Get Back Soon'
          else
            redirect_url='/products/show_cart'
            notice = 'Can not use Cash On Delivery option for this.'
          end
        end

      end
    else
      error= !params[:coupon_code].eql?('VN001') ? 'Invalid-Coupon-Code.' : 'This-Coupon-Code-is-valid-only-for-the-first-order.'
      redirect_url="/address_details/check_out?coupon_error=#{error}"
    end
    respond_to do |format|
      format.html {  redirect_to redirect_url, :notice => notice}
      format.json { render json: {:status => notice, :order_id => !@order.blank? ? @order.id : -1} }
    end
  end

  def create_order_from_payment_gateway

    is_online_payment_complete = false

    reason = 'Payment Gateway Failed'

    if !params[:mti].blank?
      @online_payment = OnlinePayment.find_by_merchant_transaction_id(params[:mti])
      if !@online_payment.blank? && @online_payment.user_id == current_user.id && @online_payment.payment_status.eql?('Success')
        CartItem.where('user_id = ? and merchant_transaction_id != ?', current_user.id, @online_payment.merchant_transaction_id).destroy_all
        @total_amount = get_total_amount
        if @online_payment.transaction_amount >= @total_amount
          @address_detail = AddressDetail.find_by_id(@online_payment.address_id)
          is_online_payment_complete = true
        else
          reason = 'Amounts do not match ' + @online_payment.transaction_amount.to_s + ' is less than ' + @total_amount
        end
      else
        reason = 'Invalid payment status ' + @online_payment.payment_status
      end
    else
      reason = 'Invalid Transcation Id'
    end
    if is_online_payment_complete
      create_order('Paid_Online', @online_payment.coupon_code)
      @online_payment.update_attribute(:order_id, @order.id)
      redirect_to "/orders/invoice_status_details?id=#{@order.id}", :notice => 'Your Order Is Taken We will Get Back Soon'
    else
      redirect_to "/products/show_cart", :notice => 'Sorry. Your payment could not be completed. Reason: ' + reason
    end

  end

  def pay_with_wallet
    @online_payment = OnlinePayment.find_by_merchant_transaction_id(params[:mti])
    @wallet_balance = get_wallet_balance
    @total_amount = get_total_amount
    @pending_amount = (@online_payment.transaction_amount - @wallet_balance).round(2)
    @pending_amount = 0 if @pending_amount <= 0
  end

  def confirm_with_wallet
    @wallet_balance = get_wallet_balance
    @total_amount = get_total_amount
    @pending_amount = @total_amount - @wallet_balance
    @pending_amount = 0 if @pending_amount <= 0
    @online_payment = OnlinePayment.find_by_merchant_transaction_id(params[:mti])

    if @pending_amount <= 0
      @wallet_entry = WalletEntry.new
      @wallet_entry.user_id = current_user.id
      @wallet_entry.amount = -@total_amount
      @wallet_entry.reason = 'Paid for order'
      @wallet_entry.transaction_id = @online_payment.merchant_transaction_id
      @wallet_entry.save!
      @online_payment.wallet_amount = @total_amount
      @online_payment.gateway_amount = 0.0
      @online_payment.payment_status = 'Paid'
      @online_payment.user_id = current_user.id
      @online_payment.save!
      redirect_to "/address_details/create_order_from_payment_gateway?mti=#{params[:mti]}"
    else
      @online_payment.wallet_amount = @wallet_balance
      @online_payment.gateway_amount = @pending_amount
      @online_payment.payment_status = 'Pending'
      @online_payment.user_id = current_user.id
      @online_payment.save!
      payment_url = cc_avenue_details(@online_payment, "#{root_url}/static/payment_response_handler")

app/helpers/address_details_helper.rb
module AddressDetailsHelper
end

app/views/address_details/_form.html.erb
<%= form_for(@address_detail) do |f| %>
  <% if @address_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@address_detail.errors.count, "error") %> prohibited this address_detail from being saved:</h2>

      <ul>
      <% @address_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :contact_number %><br />
    <%= f.text_field :contact_number %>
  </div>
  <div class="field">
    <%= f.label :house_no %><br />
    <%= f.text_field :house_no %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>
  <div class="field">
    <%= f.label :pincode %><br />
    <%= f.text_field :pincode %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :land_mark %><br />
    <%= f.text_field :land_mark %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/address_details/check_out.html.erb
<div class="checkout-container">
  <div style="padding-left: 20px;padding-right: 20px;">
    <h1 style="font-weight: 500;text-align: left">Check out</h1>
    <hr/>
    <table cellspacing="0" cellpadding="0" width="100%">
      <tr>
        <td width="70%" style="vertical-align: top">
          <div style="border: 1px solid #e0e0e0;">
            <br/>

            <div style="font-size: 16px;padding: 5px 5px 5px 15px;float: left">
              Delivery address
            </div>
            <div class="address_button">
              <a href="/address_details/new" style="text-decoration: none">Add New</a>
            </div>
            <div style="clear: both">

            </div>
            <hr style="border: 1px solid #CCC;"/>
            <table cellspacing="0" cellpadding="5">
              <%= form_tag 'create_order_with_previous_address', :method => 'post' do %>
                  <%= hidden_field_tag "address_id", 0, :id => "set_address_id" %>
                  <tr>
                    <% @address_details.each_with_index do |address, index| %>
                        <td>
                          <div id="address_box<%= index %>" onclick="select_address(<%= index %>, <%= address.id %>, <%= @address_details.size %>)" class="unselect_address_box">
                            <%= address.first_name %><br/>
                            <%= address.contact_number %><br/>
                            <%= address.house_no %><br/>
                            <%= address.area %><br/>
                            <%= address.land_mark %><br/>
                            <%= address.city %>
                            <div id="select_text<%= index %>" class="un_select_text">
                              <span>Selected</span>
                            </div>
                          </div>
                        </td>
                    <% end %>
                  </tr>


                  <tr>
                    <td colspan="3">

                      <div style="border: 1px solid #e0e0e0;">
                        <br/>

                        <div style="font-size: 16px;padding: 5px 5px 5px 15px;">
                          Select Delivery Slots
                        </div>

                        <div id="delivery-slot-information">

                        </div>

                        <hr style="border: 1px solid #CCC;"/>
                        <table cellspacing="0" cellpadding="5">
                          <% @delivery_slots.each_with_index do |slot, index| %>
                              <% is_checked = index == 0 ? true : false %>
                              <tr>
                                <td>
                                  <span style="font-size: 16px;"><%= radio_button_tag 'delivery_slot', slot.id, is_checked, :id => 'slot_id', :onclick => 'hide_delivery_time();' %>  <%= label_tag 'delivery_slot', "#{slot.slot_name}" %></span>
                                </td>
                              </tr>
                          <% end %>
                          <tr>
                            <td>
                              <span style="font-size: 16px;"><%= radio_button_tag 'delivery_slot', -999, false, :id => 'slot_id', :onclick => 'show_delivery_time(this);' %>
                                Specify your preferred delivery time</span><br/>
                              <%= text_field_tag(:chosen_delivery_time, '', :placeholder => 'Enter your preferred time', :style => 'display:none;font-size:14px;margin:10px;width:300px;padding:5px;') %>
                            </td>
                          </tr>
                          <tr>
                            <td>
                              <span style="font-size: 16px;">Coupon code.</span><br/>
                              <%= text_field_tag(:coupon_code, params[:coupon_code], :placeholder => 'Enter Coupon Code', :style => 'font-size:14px;margin:10px;width:300px;padding:5px;') %>
                                  <%= submit_tag('Apply Coupon', :class => 'apply_submit_tag') %><br/>
                              <span style=color:green><%=  params[:coupon_code].eql?('VN001') ? 'Coupon discount successfully applied.':'' %></span>
                              <%if !params[:coupon_error].blank? %>
                                  <span class="error_style"><%= params[:coupon_error].gsub('-', ' ') %></span>
                              <%end %>
                            </td>
                          </tr>
                        </table>
                        <br/>
                      </div>
                    </td>
                  </tr>
                  <tr>
                    <td style="text-align: right" colspan="3">
                      <%= submit_tag('Pay Online', :class => 'uiv2-checkout-button') %>
                      <% if !@needs_payment %>
                          <%= submit_tag('Pay Cash On Delivery', :class => 'uiv2-checkout-button') %>
                          <%= submit_tag('Pay With Sodexo/Ticket Restaurant', :class => 'uiv2-checkout-button') %>
                          <br/><span style="color: red;">* No offers/cashback when you pay with Sodexo/Ticket Restaurant</span>
                      <% end %>
                    </td>
                  </tr>
              <% end %>
            </table>
            <br/>
          </div>
        </td>
        <td width="30%" style="vertical-align: top">
          <div class="uiv2-order-summary">
            <div class="uiv2-order-summary-title">Your Order Summary</div>
            <% total_cart_items = !current_user.blank? ? CartItem.find_all_by_user_id(current_user.id) : CartItem.find_all_by_session_id(session[ApplicationHelper::SessionConstants::SESSION_ID]) %>
            <% category_lists = get_cart_by_category_level(total_cart_items) %>
            <% total_price=0 %>
            <% category_lists.each do |category_list| %>
                <div style="background-color:#dfdfdf;padding:10px 10px 10px 10px;margin-left:0px;font-size:14px;color:#000000">
                  <%= category_list.category.name %>
                </div>
                <% cart_items = category_list.cart_order_items %>
                <% cart_items.each_with_index do |item, index| %>
                    <% total_price+= item.order_item.sub_total %>
                    <div class="uiv2-sub-total">
                      <div style="float: left"><%= item.product.name %> &nbsp;&nbsp;-&nbsp;&nbsp;<%= item.order_item.quantity %>
                        <% if item.product.pre_order %>
                            <div style="color: blue;">Pre order before 48 hours</div>
                        <% end %></div>
                      <div style="float: right"><%= item.order_item.sub_total %></div>
                      <div style="clear: both"></div>
                    </div>
                <% end %>
            <% end %>
            <div class="uiv2-total-amount">
              <div style="float: left">Total Amount</div>
              <br/>
              <span style="font-size: 10px;color: red;text-transform: lowercase">(* Inclusive of all taxes)</span>

              <div style="float: right"> Rs. <%= total_price %></div>
              <div style="clear: both"></div>
            </div>
            <div class="uiv2-total-amount">
              <div style="float: left">Delivery Charges</div>
              <div style="float: right">Rs. <%= get_delivery_charges(total_price) %></div>
              <div style="clear: both"></div>
            </div>
            <%discount=0 %>
            <%if is_valid_coupon(params[:coupon_code], 'VN001') %>
                <%discount= get_discount_on_coupon(total_price) %>
            <div class="uiv2-total-amount">
              <div style="float: left">Coupon Discount</div>
              <div style="float: right;color: green">- Rs.<%= discount %></div>
              <div style="clear: both"></div>
            </div>
            <%end %>
            <div class="uiv2-amount-to-Pay-total">
              <div style="float: left">Amount to Pay</div>
              <div style="float: right"> Rs. <%= (get_delivery_charges(total_price) + (total_price-discount)).round(2) %></div>
              <div style="clear: both"></div>
            </div>
          </div>
        </td>
      </tr>
    </table>

  </div>
</div>
<script>
    function show_delivery_time(radio_selection) {
        if (radio_selection.checked) {
            $('#chosen_delivery_time').show();
            $('#chosen_delivery_time').attr('required', 'true');
        }
        else {
            hide_delivery_time();
        }
    }

    function hide_delivery_time() {
        $('#chosen_delivery_time').hide();
        $('#chosen_delivery_time').removeAttr('required');
    }
</script>
<script type="application/javascript">
    $("#address_box" + 0).removeClass('unselect_address_box').addClass('select_address_box');
    $("#select_text" + 0).removeClass('un_select_text').addClass('select_text');
    $("#set_address_id").val(<%= @address_details.first.id %>);
</script>
<script type="application/javascript">
    function select_address(index, address_id, length) {
        for (var i = length; i >= 0; i--) {
            $("#address_box" + i).removeClass('select_address_box').addClass('unselect_address_box');
            $("#select_text" + i).removeClass('select_text').addClass('un_select_text');
        }
        $("#address_box" + index).removeClass('unselect_address_box').addClass('select_address_box');
        $("#select_text" + index).removeClass('un_select_text').addClass('select_text');
        $("#set_address_id").val(address_id);
    }
</script>

app/views/address_details/edit.html.erb
<h1>Editing address_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @address_detail %> |
<%= link_to 'Back', address_details_path %>

app/views/address_details/index.html.erb
<h1>Listing address_details</h1>

<table>
  <tr>
    <th>First name</th>
    <th>Last name</th>
    <th>Contact number</th>
    <th>House no</th>
    <th>Area</th>
    <th>Pincode</th>
    <th>City</th>
    <th>Land mark</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @address_details.each do |address_detail| %>
  <tr>
    <td><%= address_detail.first_name %></td>
    <td><%= address_detail.last_name %></td>
    <td><%= address_detail.contact_number %></td>
    <td><%= address_detail.house_no %></td>
    <td><%= address_detail.area %></td>
    <td><%= address_detail.pincode %></td>
    <td><%= address_detail.city %></td>
    <td><%= address_detail.land_mark %></td>
    <td><%= link_to 'Show', address_detail %></td>
    <td><%= link_to 'Edit', edit_address_detail_path(address_detail) %></td>
    <td><%= link_to 'Destroy', address_detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Address detail', new_address_detail_path %>

app/views/address_details/pay_with_wallet.html.erb
<div class="row" style="padding: 20px ">
  <div class="col-sm-4"></div>
  <div class="col-sm-4" style="background-color: #f4a226;padding: 25px;border-radius: 10px">
    <div class="pay_with_wallet">Total Amount : <%= @total_amount %></div>
    <br/>
   <%if !@online_payment.coupon_discount.blank? %>
        <div class="pay_with_wallet">Coupon Discount : <%= @online_payment.coupon_discount %></div>
        <br/>
    <%end %>
    <div class="pay_with_wallet">Wallet Balance : <%= @wallet_balance %></div>
    <br/>

    <div class="pay_with_wallet">Amount To Be Paid : <%= @pending_amount %></div>
    <br/>

    <div align="right" style="padding: 10px">
      <a href="/address_details/confirm_with_wallet?mti=<%= params[:mti] %>" class="proceed_button">Proceed</a></div>
  </div>
</div>

app/views/address_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First name:</b>
  <%= @address_detail.first_name %>
</p>

<p>
  <b>Last name:</b>
  <%= @address_detail.last_name %>
</p>

<p>
  <b>Contact number:</b>
  <%= @address_detail.contact_number %>
</p>

<p>
  <b>House no:</b>
  <%= @address_detail.house_no %>
</p>

<p>
  <b>Area:</b>
  <%= @address_detail.area %>
</p>

<p>
  <b>Pincode:</b>
  <%= @address_detail.pincode %>
</p>

<p>
  <b>City:</b>
  <%= @address_detail.city %>
</p>

<p>
  <b>Land mark:</b>
  <%= @address_detail.land_mark %>
</p>


<%= link_to 'Edit', edit_address_detail_path(@address_detail) %> |
<%= link_to 'Back', address_details_path %>